babelfish-for-postgresql/babelfish_project_website

- Gemfile
- _config.yml
- _docs/index.md
- _faq/index.md
- _internals/postgresql-hooks.md
- _plugins/link-checker.rb
- check-links.sh
- index.markdown
Signed-off-by: Miki <mehranb@amazon.com>
* Bumped Jekyll to v4.2
* Removed github-pages dependency
* Introduced link-checker
* Normalized the links to faq
* Fixed some broken links
* Use new GA ID
> Upgrade Jekyll, add link checker, normalize some links

- .github/workflows/dco.yml
- pull_request_template.md
Signed-off-by: Miki <mehranb@amazon.com>
> Add DCO checking workflow on PRs and PR checklist

- _installation/compiling-babelfish-from-source.md
Updating installation steps
- https://github.com/babelfish-for-postgresql/babelfish_project_website/issues/91
> Updated installation steps

- .github/workflows/dco.yml
- .github/workflows/jekyll.yml
- Gemfile
- README.md
- _config.yml
- _config_CI.yml
- _docs/index.md
- _faq/index.md
- _installation/compiling-babelfish-from-source.md
- _internals/postgresql-hooks.md
- _plugins/link-checker.rb
- _sass/_babelfishpg.scss
- _sass/_style.scss
- _usage/command-line.md
- _usage/limitations-of-babelfish.md
- assets/css/custom.css
- check-links.sh
- index.markdown
- pull_request_template.md
> Prod publication

- _internals/system-views.md
Fix a type in the internals title section
- https://github.com/babelfish-for-postgresql/babelfish_project_website/issues/84
> doc: fix type in System Views title

- README.md
Added Build Badge to the website README
> Adding build badge

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/enhancement.yml
- .github/ISSUE_TEMPLATE/question.yml
> Adding issue templates

- _docs/index.md
Signed-off-by: renee2468 <renee.albe@cybertec.at>
> Change MS-SQL-to-Microsoft-SQL-Server and improve index

- _usage/migration.md
This will be interesting to people who plan to migrate to PostgreSQL for good, or who want to use the same data via TDS and the PostgreSQL protocol.
This closes #85.
> Document how to access object from PostgreSQL

- _docs/contributing.md
This is a resubmission of #107, because that branch had unsigned commits.
> Modified contributions.md to better match AWS open source guidelines

- _faq/index.md
Fixing bug report link.
This PR fixes #109 
> Fixed #109 bug report link

- _usage/migration.md
Signed-off-by: renee2468 <renee.albe@cybertec.at>
> Address issue #120 migration page in documentation

- _client/other-tools.md
- https://github.com/babelfish-for-postgresql/babelfish_project_website/issues/118
> doc: Addressing @rcv-aws suggestions

- _client/csharp.md
- _client/java.md
- _faq/index.md
- _internals/babelfish-query-handling.md
- _internals/postgresql-hooks.md
- _internals/software-architecture.md
- _internals/system-views.md
- _internals/tds-protocol.md
- _usage/command-line.md
This is a relaunch of #138.
That pull request has been approved, but cannot be committed because of merge conflicts.
> Replace "MS SQL" with "Microsoft SQL Server"

- _internals/configuration.md
- _usage/command-line.md
This is a resubmission of the changes in pull request #132,
which cannot be merged due to a conflict with 2e8ba6d45fe6ab0e4090cc6fc81b75fd2d56d320.
This closes #132, closes #115.
> Improve command line documentation

- _usage/locales.md
> Fix mistakes in the collation documentation

- _internals/tds-protocol.md
Signed-off-by: Kuntal Ghosh <kuntalgh@amazon.com>
This commit improves the documentation for end-to-end encryption of TDS connections.
#99
> Improve the documentation of SSL support for TDS connections

- README.md
- _docs/contributing.md
- _docs/writing-style-guidelines.md
> Reworked README.md file; added writing-style-guidelines.md

- _faq/index.md
Reviewed FAQ page for grammar.
> Edited FAQ page (index.md) for grammar issues

- _faq/troubleshooting.md
Reviewed/updated content on Troubleshooting page (troubleshooting.md). 
> Troubleshooting review

- DOC_STRUCTURE.md
Signed-off-by: 3manuek <emanuel@ongres.com>
Added documentation on the repository structure.
[152](https://github.com/babelfish-for-postgresql/babelfish_project_website/issues/152)
> Added documentation howto

- README.md
Updated README.md; Proofread content and fixed grammar and typos where appropriate.  Refined build sections, adding links to installation information at product sites.  Separated Writing Guidelines section into bulleted lists.  Removed Testing section, pending further discussion with team.
Adds links to installation documentation for Jekyll/Docker, reorganizes content into cohesive sections, improved grammar and voice.
> Updated README.md content

- _internals/tds-protocol.md
Updated the tds-protocol.md page; removed conversational content that didn't provide technical information, removed links to proprietary content and visuals, added links to neutral online sources, corrected voice/grammar
Updated the tds-protocol.md page to remove content that didn't provide technical information or problem resolution, removed links to proprietary content and visuals, added links to neutral (non-commercial) online resources about networking, corrected voice/grammar.  
My primary concern is that our sparse coverage of this huge topic was too open-ended, and didn't actually help the user resolve issues they might run into.  If I've removed important content that the user needs, please let me know!
See above.
By …
> tds-protocol.md update

- _installation/compiling-babelfish-from-source.md
Corrected voice, refined introductory material, fixed typos
This update corrects the voice, refines introductions (removing extra words: for example, changes 'If you happen to' to 'If you'), corrects typos. 
Updates writing.
> Updated compiling-babelfish-from-source.md

- _docs/index.md
Updated Babelfish documentation page (_docs/index.md) to correct grammar, voice, cohesion, punctuation, and spelling.
Updated Babelfish documentation page (_docs/index.md) to correct grammar, voice, cohesion, punctuation, and spelling.
The page rambled, Babelfish was misspelled, Microsoft was used a number of times, etc.
> _docs/index.md updates

- _installation/compiling-babelfish-from-source.md
- _installation/single-multiple.md
Edited single-multiple.md file to improve and clarify content, voice, tense, and grammar.
Makes the content more usable.
> Single-multiple.md update

- _usage/limitations-of-babelfish.md
As requested in https://github.com/babelfish-for-postgresql/babelfish_project_website/pull/67#discussion_r797817614.
> Remove a limitation that has been lifted

- _releases/release_notes_1.0.0.md
Added initial release notes for Babelfish 1.0.0.
Added initial release notes for Babelfish 1.0.0.
> Added initial release notes for v. 1.0.0

- _usage/command-line.md
Improved consistency of grammar and added note (per Simon) about connecting on SSMS.
This update improves the grammar in the command-line.md file, and adds warning from Simon about connecting on SSMS.
> Updated command-line.md

- _includes/releases/babelfish-1.0.0.md
Updated the babelfish-1.0.0.md file that resides in _includes/releases/babelfish-1.0.0.md.  The file is being used as both the release notes accessed from the front page of the website and the documentation release notes, and currently contains only a note that says: 1.0.0 Release Description.
Updated the babelfish-1.0.0.md file that resides in _includes/releases/babelfish-1.0.0.md.  The file is being used as both the release notes accessed from the front page of the website and the documentation release notes, and currently contains only a note that says: 1.0.0 Release Description.
By submitting this pull request, I confirm that my contribution …
> Update the babelfish-1.0.0.md file that resides in _includes/releases

- _docs/index.md
Updated index.md to correct spelling errors (Balbelfish, transitioninioning), remove extra references to Microsoft, and update the last paragraph to remove AWS and update links.
Updated index.md to correct spelling errors (Balbelfish, transitioninioning), remove extra references to Microsoft, and update the last paragraph to remove AWS and update links.
> Updated index.md for typos

- _usage/escape_hatches.md
Updated _usage/escape_hatches.md to correct navigation panel entry.
Updated _usage/escape_hatches.md to correct navigation panel entry.
Updated _usage/escape_hatches.md to correct navigation panel entry.
> Update _usage/escape_hatches.md to correct navigation panel entry

- _includes/releases/babelfish-2.1.0.md
This commit adds release notes for Babelfish version 2.1.0.
This commit adds release notes for Babelfish version 2.1.0.
> Release notes for 2.1.0

- _posts/2022-07-06-babelfish-release.md
This commit adds the blog post for the 2.1.0 release.
This commit adds the blog post for the 2.1.0 release.
> Blog post for version 2.1.0

- _artifacts/babelfish/babelfish-1.2.1-source-x64.markdown
- _artifacts/babelfish/babelfish-2.1.0-source-x64.markdown
- _includes/releases/babelfish-1.2.1.md
- _includes/releases/babelfish-2.1.0.md
- _usage/query_planning.md
- _versions/babelfish-1.2.1.md
- _versions/babelfish-2.1.0.md
- index.markdown
This PR fixes rendering issues for the releases and other markup fixes/
> Fixing Release and documentation rendering

- _usage/interoperability.md
I've updated the Interoperability page to make wording changes (recommended by Simon, approved by Rob) and remove a reference to proprietary content.
I've updated the Interoperability page to make wording changes (recommended by Simon, approved by Rob) and remove a reference to proprietary content.
I've updated the Interoperability page to make wording changes (recommended by Simon, approved by Rob) and remove a reference to proprietary content.
> Interoperability page updates

- assets/js/lib/webfontloader/webfontloader.gemspec
Update Sinatra to 2.2.0 per dependency bot alert.
> Update sinatra dependency to 2.2.0

- _usage/char_set_support.md
- _usage/limitations-of-babelfish.md
- _usage/locales.md
- _usage/migration.md
- _usage/security.md
Formatted and added Character Set Support document (from Jim Finnerty), updated order in _usage file, and edited security.md file.
Formatted and added Character Set Support document (from Jim Finnerty), updated order in _usage file so new character set document follows collations document, and edited the security.md file to make the contents less chatty, more professional.
This PR improves the _usage section.
> Added Character Set Support document and re-organized usage section

- _artifacts/babelfish/babelfish-1.3.0-source-x64.markdown
- _includes/releases/babelfish-1.3.0.md
- _versions/babelfish-1.3.0.md
I've created a readme file for Babelfish 1.3.0 - do not merge this file until release day.
Signed-off-by: susanmdouglas susandou@amazon.com
> DO NOT MERGE until 1.3.0 - README file for 1.3.0

- _artifacts/babelfish/babelfish-2.1.1-source-x64.markdown
- _includes/releases/babelfish-2.1.1.md
- _versions/babelfish-2.1.1.md
Adding release notes for 2.1.1 bug fix release; added _artifacts/babelfish/babelfish-2.1.1-source-x64.markdown, _includes/releases/babelfish-2.1.1.md, and _versions/babelfish-2.1.1.md.
I've added release notes for the 2.1.1 release, and the supporting files for the website.
I've added release notes for the 2.1.1 release, and the supporting files for the website.
> Release notes for version 2.1.1

- _artifacts/babelfish/babelfish-1.2.2-source-x64.markdown
- _includes/releases/babelfish-1.2.2.md
- _versions/babelfish-1.2.2.md
- _versions/babelfish-1.3.0.md
- _versions/babelfish-1.3.1.md
- _versions/babelfish-2.1.0a.md
- _versions/babelfish-2.1.1.md
- index.markdown
Add release notes for 1.2.2 and the website artifacts to display the release notes.  Also, fix the URLs for the 1.3.1 links and renumber the previous release content by version.
This PR contains the Release Notes for 1.2.2 and the website artifacts to display the release notes.  It also renumbers the previous release content by version.
This PR contains the Release Notes for 1.2.2 and the website artifacts to display the release notes.  It also renumbers the previous release content by version.
> Release 1.2.2

- _artifacts/babelfish/babelfish-1.1.1-source-x64.markdown
- _includes/releases/babelfish-1.1.1.md
- _versions/babelfish-1.1.1.md
- index.markdown
Adding artifacts and release notes for minor version update 1.1.1.
Adding artifacts and release notes for minor version update 1.1.1.
Adding artifacts and release notes for minor version update 1.1.1.
> Release notes for 1.1.1: Readme.md

- _artifacts/babelfish/babelfish-1.3.2-source-x64.markdown
- _includes/releases/babelfish-1.3.2.md
- _versions/babelfish-1.3.2.md
- index.markdown
Adding artifacts and release notes for minor version update 1.3.2.
Adding artifacts and release notes for minor version update 1.3.2.
Adding artifacts and release notes for minor version update 1.3.2.
> Release notes for version 1.3.2: Readme.md

- _artifacts/babelfish/babelfish-1.2.3-source-x64.markdown
- _includes/releases/babelfish-1.2.3.md
- _versions/babelfish-1.2.3.md
- index.markdown
Adding artifacts and release notes for minor version update 1.2.3.
Adding artifacts and release notes for minor version update 1.2.3.
Adding artifacts and release notes for minor version update 1.2.3.
> Release notes for version 1.2.3: Readme.md. 

- _artifacts/babelfish/babelfish-2.1.2-source-x64.markdown
- _includes/releases/babelfish-2.1.2.md
- _versions/babelfish-2.1.2.md
- index.markdown
Adding artifacts and release notes for minor version update 2.1.2.
Adding artifacts and release notes for minor version update 2.1.2.
Adding artifacts and release notes for minor version update 2.1.2.
> Release notes for version 2.1.2: Readme.md

- _artifacts/babelfish/babelfish-2.2.1-source-x64.markdown
- _includes/releases/babelfish-2.2.1.md
- _versions/babelfish-2.2.1.md
- index.markdown
This PR includes the documentation updates for release 2.2.1.
This PR includes the documentation updates for release 2.2.1.
This PR includes the documentation updates for release 2.2.1.
> DO NOT MERGE UNTIL Babelfish release 2.2.1

- _artifacts/babelfish/babelfish-1.4.1-source-x64.markdown
- _includes/releases/babelfish-1.4.1.md
- _versions/babelfish-1.4.1.md
- index.markdown
This PR contains the release notes for version 1.4.1.
This PR contains the release notes for version 1.4.1.
This PR contains the release notes for version 1.4.1.
> DO NOT MERGE UNTIL Babelfish release 1.4.1

- _artifacts/babelfish/babelfish-1.3.3-source-x64.markdown
- _includes/releases/babelfish-1.3.3.md
- _versions/babelfish-1.3.3.md
- index.markdown
Initial check in of release notes for 1.3.3
Initial check in of release notes for 1.3.3
Initial check in of release notes for 1.3.3
> DO NOT MERGE UNTIL Babelfish Release 1.3.3

- _artifacts/babelfish/babelfish-1.1.2-source-x64.markdown
- _includes/releases/babelfish-1.1.2.md
- _versions/babelfish-1.1.2.md
- index.markdown
Initial check in of release notes for version 1.1.2
Initial check in of release notes for version 1.1.2
Initial check in of release notes for version 1.1.2
> DO NOT MERGE UNTIL Babelfish release 1.1.2

- _artifacts/babelfish/babelfish-1.2.4-source-x64.markdown
- _includes/releases/babelfish-1.2.4.md
- _versions/babelfish-1.2.4.md
- index.markdown
Initial check in of release notes for version 1.2.4
Initial check in of release notes for version 1.2.4
Initial check in of release notes for version 1.2.4
> DO NOT MERGE UNTIL Babelfish release 1.2.4

- _artifacts/babelfish/babelfish-1.5.0-source-x64.markdown
- _includes/releases/babelfish-1.5.0.md
- _versions/babelfish-1.5.0.md
- index.markdown
Initial check in of release notes for 1.5.0
Initial check in of release notes for 1.5.0
Initial check in of release notes for 1.5.0
> DO NOT MERGE UNTIL 1.5.0 - Release Notes

- _posts/2023-12-12-babelfish-wesite-announcement.markdown
Introducing GitHub discussion and wiki page. Adding the announcement in the website.
> Important Website announcement

- _posts/2024-2-21-babelfish-release-4-0-0.markdown
Announce Babelfish support for PostgreSQL 16
> Announce Babelfish support for PostgreSQL 16

- _workaround/workarounds_toc.md
Remove default param link from workarounds page list
> Remove default param link from workarounds page list

- _usage/locales.md
Update references for 
Chinese_CS_AS to Chinese_PRC_CS_AS,
Chinese_CI_AS to Chinese_PRC_CI_AS,
Chinese_CI_AI to Chinese_PRC_CI_AI
> Update Deterministic and non-deterministic collation info for Chinese collations
