babelfish-for-postgresql/babelfish_project_website

.github/workflows/jekyll.yml, README.md, _config_CI.yml
Fixes CI build url by setting a different configuration file.
https://github.com/babelfish-for-postgresql/babelfish_project_website/issues/74
=> Fixing CI publishing

_installation/compiling-babelfish-from-source.md
Correct product name is "Babelfish for PostgreSQL", and `libxslt` was typo'd as `libxstl'.
Replaces PR #75 (which had unsigned commits).
=> Fix product name and a minor typo

_docs/contributing.md, _docs/vision.md
In "vision":
- Fix bad grammar.
- Spell out the product instead of abbreviating it as "MS SQL".
In "contributing":
- Rewrite the requirement to add documentation with your contribution and move the parts that deal with tests to the preceding section.
Per request from @susanmdouglas-aws.
This closes #89.
=> Improve "vision" and "contributing" doc

_installation/single-multiple.md
Copiously copied from the Amazon Babelfish documentation.
=> Improve documentation "single-db" vs. "multi-db"

_internals/software-architecture.md
Several changes, among them:
- avoid words like "emulate" that might insinuate inferior performance
- replace "MS SQL" with "Microsoft SQL Server"
- remove redundant and overly chatty phrases and sentences
- improve the English
- fix the wrong assertion that SQL Server does not have schemas
- fix wrong assertions regarding the migration mode
- use backticks instead of &lt;code&gt; markup
- remove trailing whitespace
=> Improve the architecture documentation

_usage/limitations-of-babelfish.md
- revamp the introductory paragraph
- the 3-millisocond limitation on `DATETIME` is gone
- change heading from "Dealing with limitations" to "Babelfish escape hatches"
and remove the first paragraph in that section
- don't use "script" to refer to a "procedure"
- fix the setting to `ignore` rather than `ignored`
- be explicit that changes to escape hatches with `server` are persistent
- mention that some escape hatches are enabled by default and describe
how to disable them globally
- rework the escape hatches list to a table
- copy escape hatch description from the Amazon page, fixing typos
and bad grammar where appropriate
- cosmetic change: remove unnecessary backslash before single quotes
This closes #124.
=> Improve the "limitations" page some more

_internals/software-architecture.md
Since this is just a copy of the 2ndQuadrant software, it is silly to add usage instructions and internal details.
Rather, point to the original documentation.
This closes #103.
Not that this commit doesn't touch any of the other problems in the data type documentation, in order to reduce merge conflicts
with a prospective patch that addresses #102 once we have the required information.
=> Replace "babelfish_money" documentation with a link

_usage/security.md
The existing documentation was inaccurate and confusing.
This tries to address #121.
=> Improve user management documentation

_installation/compiling-babelfish-from-source.md
When people want to install Babelfish, they will read the "compilation from source" page.  However, that page does not mention that you need to initialze Babelfish.
The reader is left thinking that Babelfish is ready to use once the server is started.
Add a link to the "single-db vs. multi-db setup" page.
=> Add a link to finish Babelfish setup

_usage/locales.md
This addresses issue #125.
- Avoid the term "collation ID" where not appropriate.
- Fix the table of server collations to list the case sensitive collations.
- Improve the description of the CP1 collation.
- State that the "object collations" table is actually collations you can use to support more than one locale in your database.
- Improve the description of the "General" collation.
- Fix the description of Unicode sorting rules.
- Fix the description of secondary-equal collations.
- Fix the workaround for tertiary collations.
- Fix the completely messed up paragraph on ICU collation differences.
- Some English language and style fixes.
- Remove the unnecessary backslash before single quotes and use backticks for code formatting.
@JimFinnerty: I am sure that I missed some things. For …
=> Improve collation documentation

_internals/configuration.md
Updated documentation about the `babelfishpg_tsql.use_antlr` setting, according to [Sangil's comment at Issue 47](https://github.com/babelfish-for-postgresql/babelfish_extensions/issues/47#issuecomment-994107040) in the babelfish_extensions repository.
=> Extended information about babelfishpg_tsql.use_antlr

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/documentation.yml, .github/ISSUE_TEMPLATE/enhancement.yml
Signed-off-by: 3manuek <emanuel@ongres.com>
- Added documentation issue template.
- Fixes on templates wording.
=> feat: Adding documentation and fixes to issue templates

_internals/software-architecture.md
Architecture page edits
This PR replaces #126.  This page discusses the architectural differences between Babelfish and community PostgreSQL. 
This patch fixes grammar and chattiness in the original document, and removes excessive exclamation points, questions, and company references.  Removes specific port values,  documents the purpose of each extension, removes the list of unsupported datatypes (that information is already in the Limitations documentation).
=> Reworked/worded _internals/software-architecture.md

_usage/command-line.md
The "SSMS Object Explorer support limitation" sentence has been moved to a quote, considering that the original documentation does this emphasis. 
References:
- [Babelfish original documentation](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/babelfish-connect-sqlserver.html#babelfish-connect-SSMS)
- [Issue #55](https://github.com/babelfish-for-postgresql/babelfish_extensions/issues/55)
=> Highlighted SSMS OE limitation in a quote

README.md
The link to the Docker website erroneously pointed to the Jekyll website... I've updated it with this commit.
Fixed a bad link.
=> Fixed broken link to Docker website in README.md file

README.md
Updated links in navigation section of README.md file; some of the links at the top of the page are no longer available.
Removed or replaced links at top of README.md file.
Some of the links at the top of the page are no longer available.
=> Updated links on Babelfish README.md 

.github/ISSUE_TEMPLATE/documentation.yml, _data/repos.yml, _docs/index.md, _installation/compiling-babelfish-from-source.md
This PR contains the necessary updates for the `BABEL_1_0_0` release (WIP fixes on tags):
- Updated tags across documentation and templates.
- Bumped ANLTR version to 4.9.3 according to [PR 66 in babelfish_extensions](https://github.com/babelfish-for-postgresql/babelfish_extensions/pull/66#pullrequestreview-868040254)
=> Bump version tag to BABEL_1_0_0

_config.yml, _includes/nav.html, _layouts/default.html
Signed-off-by: ldgarcia <lgarcia@ongres.com>
Enable descending order for versions list on the navigation sidebar
#205 
=> Enable descending order for versions list on the navigation sidebar

_usage/interoperability.md
This commit adds the Interoperability document shared by Rob Verschoor; the document contrasts the behaviors of the PG and TDS ports, and discusses the positive and negative ramifications of using both ports for transactions on the same database.
This commit adds the Interoperability document shared by Rob.
=> Add interoperability documentation

_includes/releases/babelfish-2.1.0.md, _posts/2022-07-06-babelfish-release.md
I've updated _posts/2022-07-06-babelfish-release.md to fix a broken link; the link was previously pointing to release notes for a different version.  I've also added a note to the release notes for 2.1.0  that this release also backported the fix from the PostgreSQL 14.4 community release that reverts changes to CONCURRENTLY.
I've updated _posts/2022-07-06-babelfish-release.md to fix a broken link; the link was previously pointing to release notes for a different version.  I've also added a note to the release notes for 2.1.0  that this release also backported the fix from the PostgreSQL 14.4 community release that reverts changes to CONCURRENTLY.
I've updated _posts/2022-07-06-babelfish-release.md to fix a broken link; the link was …
=> Fixes for 2.1.0 blog post and release notes

_includes/releases/babelfish-2.1.0.md
I've updated the release notes for 2.1.0 (_includes/releases/babelfish-2.1.0.md) to remove mention of the backpatching of the CONCURRENTLY problem from the community, and updated the release date. We may or may not need to merge this change, but I'd like to have it on hand in case we need it.
I've updated the release notes for 2.1.0 (_includes/releases/babelfish-2.1.0.md) to remove mention of the backpatching of the CONCURRENTLY problem from the community, and updated the release date. We may or may not need to merge this change, but I'd like to have it on hand in case we need it.
I've updated the release notes for 2.1.0 (_includes/releases/babelfish-2.1.0.md) to remove mention of the backpatching of the CONCURRENTLY problem from the …
=> Remove mention of backpatching for CONCURRENTLY issue from release notes

_includes/releases/babelfish-1.3.1.md, _includes/releases/babelfish-2.1.1.md, index.markdown
This PR fixes the values displayed for the download links in the release notes, and adds the 2.1.1 release to the front page of the website.
This PR fixes the values displayed for the download links in the release notes, and adds the 2.1.1 release to the front page of the website.
=> Fix 2.1.1 and 1.3.1 displayed values for download links

_limitations/limitations-of-babelfish.md, _limitations/usf_2.2.0.md
This PR contains the _limitations/limitations-of-babelfish.md table, updated for release 2.2.0 (in case the separate script-produced files aren't ready yet).
This PR contains the _limitations/limitations-of-babelfish.md table, updated for release 2.2.0 (in case the separate script-produced files aren't ready yet).
This PR contains the _limitations/limitations-of-babelfish.md table, updated for release 2.2.0 (in case the separate script-produced files aren't ready yet).
=> DO NOT MERGE Until Version 2.2.0 - updated Limitations Table

_usage/hint_mapping.md
Initial check in of hint mapping for 2.3.0
Initial check in of hint mapping for 2.3.0
Initial check in of hint mapping for 2.3.0
=> DO NOT MERGE UNTIL 2.3.0. - Babelfish support for hint mapping

_usage/locales.md
Signed-off-by: vasavi suthapalli <svasusri@amazon.com>
Updated locales.md to correct sentence from 'SELECT * FROM fn_helpcollation();' to 'SELECT * FROM fn_helpcollations();'
=> Updated locales.md for typos
